[package]
name = "blas"
version = "0.1.0"
edition = "2021"

[dependencies]
blas-src = { version = "0.10", features = ["openblas"] }
blas = "0.22.0"
openblas-src = { version = "0.10", features = ["system"] }
matrix_base = { path = "../matrix_base" }
