[package]
name = "workspace_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
matrix_base = { path = "../matrix_base" }
fakscpu = {path = "../cpu"}
cublas = {path = "../cublas"}
cusparse = {path = "../cusparse"}
blas_dense = { path = "../blas" }