[package]
name = "workspace_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
matrix_base = { path = "../matrix_base" }
cublas = {path = "../cublas"}
cusparse = {path = "../cusparse"}
gpu = { path = "../gpu" }
fakscpu = {path = "../cpu"}